name: Daily Phone Case automation
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install sharp
      - run: node phone_case_automation.js
        env:
          NB_API_KEY: ${{ secrets.NB_API_KEY }}
          PRINTIFY_API_KEY: ${{ secrets.PRINTIFY_API_KEY }}
